version: '3.3'

volumes:
  pg_data:
  static:
  media:
  frontend:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  frontend:
    image: ilhambalat/foodgram_frontend
    volumes:
      - frontend:/app/result_build/build/
  backend:
    image: ilhambalat/foodgram_backend
    env_file: .env
    volumes:
      - static:/app/collected_static
      - media:/app/media
  nginx:
    image: ilhambalat/foodgram_nginx
    ports:
      - 8888:80
    volumes:
      - frontend:/usr/share/nginx/html/
      - static:/static
      - media:/media
